global using Xunit;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Orleans.Runtime;
global using Orleans.TestingHost;
global using OrleansBook.GrainInterfaces;
global using OrleansBook.Grains.Dtos;
global using OrleansBook.Grains;